dist: trusty
sudo: false

language: node_js
node_js:
- "8"

script:
  - npm run-script generate-locals
  - npm run-script generate-redirects
  - npm run-script build
  # Because we build again, move the non-deploy build out of the way.
   - mv build test-build

before_deploy:
  - openssl aes-256-cbc -in secrets.tar.enc -out secrets.tar.out -d -pass "env:encrypted_client_secrets_password"
  - tar xvf secrets.tar
  - npm run-script ci:import
  - npm run-script build
  - node tests/post-build.js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  on:
    branch: master

